[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "14"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mermaid.cli"]

[functions."generatePDF"]
  timeout = 30

[[plugins]]
package = "@netlify/plugin-functions-install-core"